# Generated by Django 5.2.3 on 2025-07-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_catagory_event_category_remove_event_dete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='event',
            new_name='events',
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
