# Generated by Django 5.2.3 on 2025-07-10 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_event_participant_events_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvps',
            field=models.ManyToManyField(blank=True, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
