# Generated by Django 5.2.3 on 2025-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_rsvps'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/Default.jpg', upload_to='event_images/'),
        ),
    ]
