# Generated by Django 5.2.3 on 2025-07-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/Default.jpg', null=True, upload_to='event_images/'),
        ),
    ]
